# Generated by Django 4.2.2 on 2023-07-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='', max_length=228),
            preserve_default=False,
        ),
    ]
