# Generated by Django 4.2.2 on 2023-07-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_products_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
