# Generated by Django 4.2.2 on 2023-07-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_categorie_product_categorie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categorie',
            new_name='category',
        ),
    ]
