# Generated by Django 4.2.2 on 2023-09-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_productpack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpack',
            name='products',
        ),
        migrations.AddField(
            model_name='productpack',
            name='products',
            field=models.ManyToManyField(default=True, to='store.product'),
        ),
    ]
