# Generated by Django 4.2.2 on 2023-09-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_productpack_products_productpack_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpack',
            name='products',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
