# Generated by Django 4.2.2 on 2023-09-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_productpack_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpack',
            name='prices',
            field=models.FloatField(default=0),
        ),
    ]
