# Generated by Django 4.2.8 on 2023-12-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_alter_cart_user_alter_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="product"),
        ),
    ]
