# Generated by Django 4.2.3 on 2024-01-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_product_thumbnail'),
        ('store', '0022_order_total_price_alter_product_thumbnail'),
    ]

    operations = [
    ]
