# Generated by Django 4.2.3 on 2024-01-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_product_discount_price_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
