# Generated by Django 4.2.5 on 2023-10-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_shopper_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopper',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
