# Generated by Django 4.2.5 on 2023-10-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0003_alter_shopper_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopper',
            name='groups',
            field=models.ManyToManyField(related_name='shopper', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='user_permissions',
            field=models.ManyToManyField(related_name='shopper_user_permissions', to='auth.permission'),
        ),
    ]
